from .columns_to_postprocess import LANE_COLUMNS, GAME_COLUMNS, SUM_TOTAL_DATA, AVERAGE_TOTAL_DATA, \
    PERCENTAGE_DATA, COMPARE_DATA_CORES, COMPARE_DATA_SUPPORT, ALL_DATA_TO_COMPARE, MAX_TOTAL_DATA
from .postprocessor import postprocess_data
