class GamePerformanceConstant:
    MATCH_DATA: int = 1
    MATCH_DATA_COMPARISON: int = 2

    AGGREGATION: int = 3
    AGGREGATION_COMPARISON: int = 4

    # MADE USING NORMAL DATA
    CROSS_COMPARISON: int = 5
    # MADE USING COMPARISON DATA
    CROSS_COMPARISON_COMPARISON: int = 6
