HERO_DATA = {
    1: {'name': 'antimage',
        'id': 1,
        'localized_name': 'Anti-Mage',
        'summons': []},
    2: {'name': 'axe', 'id': 2, 'localized_name': 'Axe', 'summons': []},
    3: {'name': 'bane', 'id': 3, 'localized_name': 'Bane', 'summons': []},
    4: {'name': 'bloodseeker',
        'id': 4,
        'localized_name': 'Bloodseeker',
        'summons': []},
    5: {'name': 'crystal_maiden',
        'id': 5,
        'localized_name': 'Crystal Maiden',
        'summons': []},
    6: {'name': 'drow_ranger',
        'id': 6,
        'localized_name': 'Drow Ranger',
        'summons': []},
    7: {'name': 'earthshaker',
        'id': 7,
        'localized_name': 'Earthshaker',
        'summons': []},
    8: {'name': 'juggernaut',
        'id': 8,
        'localized_name': 'Juggernaut', 'pseudosummons': True,
        'summons': ['npc_dota_juggernaut_healing_ward', ]},
    9: {'name': 'mirana', 'id': 9, 'localized_name': 'Mirana', 'summons': []},
    11: {'name': 'nevermore',
         'id': 11,
         'localized_name': 'Shadow Fiend',
         'summons': []},
    10: {'name': 'morphling',
         'id': 10,
         'localized_name': 'Morphling',
         'summons': []},
    12: {'name': 'phantom_lancer',
         'id': 12,
         'localized_name': 'Phantom Lancer',
         'summons': []},
    13: {'name': 'puck', 'id': 13, 'localized_name': 'Puck', 'summons': []},
    14: {'name': 'pudge', 'id': 14, 'localized_name': 'Pudge', 'summons': []},
    15: {'name': 'razor', 'id': 15, 'localized_name': 'Razor', 'pseudosummons': True,
         'summons': ['npc_dota_plasma_field']},
    16: {'name': 'sand_king',
         'id': 16,
         'localized_name': 'Sand King',
         'summons': []},
    17: {'name': 'storm_spirit',
         'id': 17,
         'localized_name': 'Storm Spirit', 'pseudosummons': True,
         'summons': ['npc_dota_stormspirit_remnant', ]},
    18: {'name': 'sven', 'id': 18, 'localized_name': 'Sven', 'summons': []},
    19: {'name': 'tiny', 'id': 19, 'localized_name': 'Tiny', 'summons': []},
    20: {'name': 'vengefulspirit',
         'id': 20,
         'localized_name': 'Vengeful Spirit',
         'summons': []},
    21: {'name': 'windrunner',
         'id': 21,
         'localized_name': 'Windranger',
         'summons': []},
    22: {'name': 'zuus', 'id': 22, 'localized_name': 'Zeus', 'summons': []},
    23: {'name': 'kunkka', 'id': 23, 'localized_name': 'Kunkka', 'summons': []},
    25: {'name': 'lina', 'id': 25, 'localized_name': 'Lina', 'summons': []},
    31: {'name': 'lich', 'id': 31, 'localized_name': 'Lich', 'summons': []},
    26: {'name': 'lion', 'id': 26, 'localized_name': 'Lion', 'summons': []},
    27: {'name': 'shadow_shaman',
         'id': 27,
         'localized_name': 'Shadow Shaman', 'pseudosummons': True,
         'summons': ['npc_dota_shadow_shaman_ward_1',
                     'npc_dota_shadow_shaman_ward_2',
                     'npc_dota_shadow_shaman_ward_3', ]},
    28: {'name': 'slardar', 'id': 28, 'localized_name': 'Slardar', 'summons': []},
    29: {'name': 'tidehunter',
         'id': 29,
         'localized_name': 'Tidehunter',
         'summons': []},
    30: {'name': 'witch_doctor', 'pseudosummons': True,
         'id': 30,
         'localized_name': 'Witch Doctor',
         'summons': ['npc_dota_witch_doctor_death_ward']},
    32: {'name': 'riki', 'id': 32, 'localized_name': 'Riki', 'summons': []},
    33: {'name': 'enigma', 'id': 33, 'localized_name': 'Enigma', 'summons': ['npc_dota_dire_eidolon',
                                                                             'npc_dota_eidolon',
                                                                             'npc_dota_greater_eidolon',
                                                                             'npc_dota_lesser_eidolon', ]},
    34: {'name': 'tinker', 'id': 34, 'localized_name': 'Tinker', 'summons': []},
    35: {'name': 'sniper', 'id': 35, 'localized_name': 'Sniper', 'summons': []},
    36: {'name': 'necrolyte',
         'id': 36,
         'localized_name': 'Necrophos',
         'summons': []},
    37: {'name': 'warlock', 'id': 37, 'localized_name': 'Warlock', 'summons': ['npc_dota_warlock_golem_1',
                                                                               'npc_dota_warlock_golem_2',
                                                                               'npc_dota_warlock_golem_3',
                                                                               'npc_dota_warlock_golem_scepter_1',
                                                                               'npc_dota_warlock_golem_scepter_2',
                                                                               'npc_dota_warlock_golem_scepter_3', ]},
    38: {'name': 'beastmaster',
         'id': 38,
         'localized_name': 'Beastmaster',
         'summons': ['npc_dota_beastmaster_boar',
                     'npc_dota_beastmaster_greater_boar',
                     'npc_dota_greater_hawk',
                     'npc_dota_scout_hawk', ]},
    39: {'name': 'queenofpain',
         'id': 39,
         'localized_name': 'Queen of Pain',
         'summons': []},
    40: {'name': 'venomancer',
         'id': 40,
         'localized_name': 'Venomancer', 'pseudosummons': True,
         'summons': ['npc_dota_venomancer_plague_ward_1',
                     'npc_dota_venomancer_plague_ward_2',
                     'npc_dota_venomancer_plague_ward_3',
                     'npc_dota_venomancer_plague_ward_4', ]},
    41: {'name': 'faceless_void',
         'id': 41,
         'localized_name': 'Faceless Void',
         'summons': []},
    42: {'name': 'skeleton_king',
         'id': 42,
         'localized_name': 'Wraith King',
         'summons': ['npc_dota_wraith_king_skeleton_warrior', ]},
    43: {'name': 'death_prophet',
         'id': 43,
         'localized_name': 'Death Prophet', 'pseudosummons': True,
         'summons': []},
    44: {'name': 'phantom_assassin',
         'id': 44,
         'localized_name': 'Phantom Assassin',
         'summons': []},
    45: {'name': 'pugna', 'id': 45, 'pseudosummons': True,
         'localized_name': 'Pugna', 'summons': ['npc_dota_pugna_nether_ward_1',
                                                'npc_dota_pugna_nether_ward_2',
                                                'npc_dota_pugna_nether_ward_3',
                                                'npc_dota_pugna_nether_ward_4', ]},
    46: {'name': 'templar_assassin',
         'id': 46,
         'localized_name': 'Templar Assassin',
         'summons': ['npc_dota_templar_assassin_psionic_trap', ]},
    47: {'name': 'viper', 'id': 47, 'localized_name': 'Viper', 'summons': []},
    48: {'name': 'luna', 'id': 48, 'localized_name': 'Luna', 'summons': []},
    49: {'name': 'dragon_knight',
         'id': 49,
         'localized_name': 'Dragon Knight',
         'summons': []},
    50: {'name': 'dazzle', 'id': 50, 'localized_name': 'Dazzle', 'summons': []},
    51: {'name': 'rattletrap',
         'id': 51,
         'localized_name': 'Clockwerk', 'pseudosummons': True,
         'summons': ['npc_dota_rattletrap_cog',
                     'npc_dota_rattletrap_rocket', ]},
    52: {'name': 'leshrac', 'id': 52, 'localized_name': 'Leshrac', 'summons': []},
    53: {'name': 'furion',
         'id': 53,
         'localized_name': "Nature's Prophet",
         'summons': ['npc_dota_furion_treant', ]},
    54: {'name': 'life_stealer',
         'id': 54,
         'localized_name': 'Lifestealer',
         'summons': []},
    55: {'name': 'dark_seer',
         'id': 55,
         'localized_name': 'Dark Seer',
         'summons': []},
    56: {'name': 'clinkz', 'id': 56, 'localized_name': 'Clinkz', 'summons': []},
    57: {'name': 'omniknight',
         'id': 57,
         'localized_name': 'Omniknight',
         'summons': []},
    58: {'name': 'enchantress',
         'id': 58,
         'localized_name': 'Enchantress',
         'summons': []},
    59: {'name': 'huskar', 'id': 59, 'localized_name': 'Huskar', 'summons': []},
    60: {'name': 'night_stalker',
         'id': 60,
         'localized_name': 'Night Stalker',
         'summons': []},
    61: {'name': 'broodmother',
         'id': 61,
         'localized_name': 'Broodmother',
         'summons': ['npc_dota_broodmother_spiderite',
                     'npc_dota_broodmother_spiderling',
                     'npc_dota_broodmother_web', ]},
    62: {'name': 'bounty_hunter',
         'id': 62,
         'localized_name': 'Bounty Hunter',
         'summons': []},
    63: {'name': 'weaver', 'id': 63, 'localized_name': 'Weaver', 'summons': ['npc_dota_weaver_swarm', ]},
    64: {'name': 'jakiro', 'id': 64, 'localized_name': 'Jakiro', 'summons': []},
    65: {'name': 'batrider',
         'id': 65,
         'localized_name': 'Batrider',
         'summons': []},
    66: {'name': 'chen', 'id': 66, 'localized_name': 'Chen', 'summons': []},
    67: {'name': 'spectre', 'id': 67, 'localized_name': 'Spectre', 'summons': []},
    69: {'name': 'doom_bringer',
         'id': 69,
         'localized_name': 'Doom',
         'summons': []},
    68: {'name': 'ancient_apparition',
         'id': 68,
         'localized_name': 'Ancient Apparition',
         'summons': []},
    70: {'name': 'ursa', 'id': 70, 'localized_name': 'Ursa', 'summons': []},
    71: {'name': 'spirit_breaker',
         'id': 71,
         'localized_name': 'Spirit Breaker',
         'summons': []},
    72: {'name': 'gyrocopter', 'pseudosummons': True,
         'id': 72,
         'localized_name': 'Gyrocopter',
         'summons': ['npc_dota_gyrocopter_homing_missile', ]},
    73: {'name': 'alchemist',
         'id': 73,
         'localized_name': 'Alchemist',
         'summons': []},
    74: {'name': 'invoker', 'id': 74, 'localized_name': 'Invoker',
         'summons': ['npc_dota_invoker_forged_spirit', ]},
    75: {'name': 'silencer',
         'id': 75,
         'localized_name': 'Silencer',
         'summons': []},
    76: {'name': 'obsidian_destroyer',
         'id': 76,
         'localized_name': 'Outworld Destroyer',
         'summons': []},
    77: {'name': 'lycan', 'id': 77, 'localized_name': 'Lycan', 'summons': [
        'npc_dota_lycan_wolf1',
        'npc_dota_lycan_wolf2',
        'npc_dota_lycan_wolf3',
        'npc_dota_lycan_wolf4',
    ]},
    78: {'name': 'brewmaster',
         'id': 78,
         'localized_name': 'Brewmaster', 'pseudosummons': True,
         'summons': ['npc_dota_brewmaster_earth_1',
                     'npc_dota_brewmaster_earth_2',
                     'npc_dota_brewmaster_earth_3',
                     'npc_dota_brewmaster_fire_1',
                     'npc_dota_brewmaster_fire_2',
                     'npc_dota_brewmaster_fire_3',
                     'npc_dota_brewmaster_storm_1',
                     'npc_dota_brewmaster_storm_2',
                     'npc_dota_brewmaster_storm_3', ]},
    79: {'name': 'shadow_demon',
         'id': 79,
         'localized_name': 'Shadow Demon',
         'summons': ['npc_dota_shadow_shaman_ward_1',
                     'npc_dota_shadow_shaman_ward_2',
                     'npc_dota_shadow_shaman_ward_3', ]},
    80: {'name': 'lone_druid',
         'id': 80,
         'localized_name': 'Lone Druid',
         'summons': ['npc_dota_lone_druid_bear1',
                     'npc_dota_lone_druid_bear2',
                     'npc_dota_lone_druid_bear3',
                     'npc_dota_lone_druid_bear4', ]},
    81: {'name': 'chaos_knight',
         'id': 81,
         'localized_name': 'Chaos Knight',
         'summons': []},
    82: {'name': 'meepo', 'id': 82, 'localized_name': 'Meepo', 'summons': []},
    83: {'name': 'treant',
         'id': 83,
         'localized_name': 'Treant Protector',
         'summons': []},
    84: {'name': 'ogre_magi',
         'id': 84,
         'localized_name': 'Ogre Magi',
         'summons': []},
    85: {'name': 'undying', 'id': 85, 'localized_name': 'Undying', 'pseudosummons': True,
         'summons': ['npc_dota_unit_tombstone1',
                     'npc_dota_unit_tombstone2',
                     'npc_dota_unit_tombstone3',
                     'npc_dota_unit_tombstone4',
                     'npc_dota_unit_undying_zombie',
                     'npc_dota_unit_undying_zombie_torso', ]},
    86: {'name': 'rubick', 'id': 86, 'localized_name': 'Rubick', 'summons': []},
    87: {'name': 'disruptor',
         'id': 87,
         'localized_name': 'Disruptor',
         'summons': []},
    88: {'name': 'nyx_assassin',
         'id': 88,
         'localized_name': 'Nyx Assassin',
         'summons': []},
    89: {'name': 'naga_siren',
         'id': 89,
         'localized_name': 'Naga Siren',
         'summons': []},
    90: {'name': 'keeper_of_the_light',
         'id': 90,
         'localized_name': 'Keeper of the Light',
         'summons': []},
    91: {'name': 'wisp', 'id': 91, 'localized_name': 'Io', 'summons': ['npc_dota_wisp_spirit', ]},
    92: {'name': 'visage', 'id': 92, 'localized_name': 'Visage', 'summons': ['npc_dota_visage_familiar1',
                                                                             'npc_dota_visage_familiar2',
                                                                             'npc_dota_visage_familiar3', ]},
    93: {'name': 'slark', 'id': 93, 'localized_name': 'Slark', 'summons': []},
    94: {'name': 'medusa', 'id': 94, 'localized_name': 'Medusa', 'summons': []},
    95: {'name': 'troll_warlord',
         'id': 95,
         'localized_name': 'Troll Warlord', 'pseudosummons': True,
         'summons': ['npc_dota_troll_warlord_axe', ]},
    96: {'name': 'centaur',
         'id': 96,
         'localized_name': 'Centaur Warrunner',
         'summons': []},
    97: {'name': 'magnataur',
         'id': 97,
         'localized_name': 'Magnus',
         'summons': []},
    98: {'name': 'shredder',
         'id': 98,
         'localized_name': 'Timbersaw',
         'summons': []},
    99: {'name': 'bristleback',
         'id': 99,
         'localized_name': 'Bristleback',
         'summons': []},
    100: {'name': 'tusk', 'id': 100, 'pseudosummons': True,
          'localized_name': 'Tusk', 'summons': ['npc_dota_tusk_frozen_sigil1',
                                                'npc_dota_tusk_frozen_sigil2',
                                                'npc_dota_tusk_frozen_sigil3',
                                                'npc_dota_tusk_frozen_sigil4', ]},
    101: {'name': 'skywrath_mage',
          'id': 101,
          'localized_name': 'Skywrath Mage',
          'summons': []},
    102: {'name': 'abaddon',
          'id': 102,
          'localized_name': 'Abaddon',
          'summons': []},
    103: {'name': 'elder_titan',
          'id': 103,
          'localized_name': 'Elder Titan', 'pseudosummons': True,
          'summons': ['npc_dota_elder_titan_ancestral_spirit', ]},
    104: {'name': 'legion_commander',
          'id': 104,
          'localized_name': 'Legion Commander',
          'summons': []},
    106: {'name': 'ember_spirit',
          'id': 106,
          'localized_name': 'Ember Spirit', 'pseudosummons': True,
          'summons': ['npc_dota_ember_spirit_remnant', ]},
    107: {'name': 'earth_spirit',
          'id': 107,
          'localized_name': 'Earth Spirit', 'pseudosummons': True,
          'summons': ['npc_dota_earth_spirit_stone', ]},
    108: {'name': 'abyssal_underlord',
          'id': 108,
          'localized_name': 'Underlord',
          'summons': []},
    109: {'name': 'terrorblade',
          'id': 109,
          'localized_name': 'Terrorblade',
          'summons': []},
    110: {'name': 'phoenix',
          'id': 110,
          'localized_name': 'Phoenix',
          'summons': ['npc_dota_phoenix_sun', ]},
    105: {'name': 'techies',
          'id': 105,
          'localized_name': 'Techies', 'pseudosummons': True,
          'summons': ['npc_dota_techies_land_mine',
                      'npc_dota_techies_remote_mine',
                      'npc_dota_techies_stasis_trap', ]},
    111: {'name': 'oracle', 'id': 111, 'localized_name': 'Oracle', 'summons': []},
    112: {'name': 'winter_wyvern',
          'id': 112,
          'localized_name': 'Winter Wyvern',
          'summons': []},
    113: {'name': 'npc_dota_hero_arc_warden',
          'id': 113,
          'localized_name': 'Arc Warden',
          'summons': []},
    114: {'name': 'monkey_king',
          'id': 114,
          'localized_name': 'Monkey King',
          'summons': []},
    119: {'name': 'dark_willow',
          'id': 119,
          'localized_name': 'Dark Willow',
          'summons': []},
    120: {'name': 'pangolier',
          'id': 120,
          'localized_name': 'Pangolier',
          'summons': []},
    121: {'name': 'grimstroke',
          'id': 121,
          'localized_name': 'Grimstroke',
          'summons': []},
    123: {'name': 'hoodwink',
          'id': 123,
          'localized_name': 'Hoodwink',
          'summons': []},
    126: {'name': 'void_spirit',
          'id': 126,
          'localized_name': 'Void Spirit',
          'summons': []},
    128: {'name': 'snapfire',
          'id': 128,
          'localized_name': 'Snapfire',
          'summons': []},
    129: {'name': 'mars', 'id': 129, 'localized_name': 'Mars', 'summons': []},
    135: {'name': 'dawnbreaker',
          'id': 135,
          'localized_name': 'Dawnbreaker',
          'summons': []},
    136: {'name': 'marci', 'id': 136, 'localized_name': 'Marci', 'summons': []},
    137: {'name': 'primal_beast',
          'id': 137,
          'localized_name': 'Primal Beast',
          'summons': []},
    138: {'name': 'muerta', 'id': 138, 'localized_name': 'Muerta', 'summons': []},
    'summons': ['npc_dota_necronomicon_archer_1',
                'npc_dota_necronomicon_archer_2',
                'npc_dota_necronomicon_archer_3',
                'npc_dota_necronomicon_warrior_1',
                'npc_dota_necronomicon_warrior_2',
                'npc_dota_necronomicon_warrior_3', ]
}
