services:
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mx
      - POSTGRES_PASSWORD=ghbdtn
      - POSTGRES_DB=dota
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/dota
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  parser:
    image: odota/parser
    ports:
      - "5600:5600"