from tasks.aggregation.delete import delete_aggregation_match, delete_aggregation_team
from tasks.aggregation.player.player import aggregate_league_player_task
from tasks.aggregation.team.team import aggregate_league_team_task
