from tasks.cross_comparison.delete import delete_cross_comparison_team, delete_cross_comparison_match
from tasks.cross_comparison.match import cross_compare_player_task
from tasks.cross_comparison.team import cross_compare_team_task
