"""script

Revision ID: 1f57ab5b4773
Revises: 6af7ef7b6b2f
Create Date: 2025-03-30 21:31:04.394758

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes
from sqlmodel.orm.session import Session

from alembic import op
import sqlalchemy as sa

from scripts.populate_all import populate_all


# revision identifiers, used by Alembic.
revision: str = '1f57ab5b4773'
down_revision: Union[str, None] = '6af7ef7b6b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        populate_all(sqlmodel_session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
