"""agg_info_bool

Revision ID: 048f5472067b
Revises: e082f48fedaf
Create Date: 2024-03-13 22:38:38.795834

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048f5472067b'
down_revision: Union[str, None] = 'e082f48fedaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_data_types', sa.Column('sum_to_agg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_data_types', 'sum_to_agg')
    # ### end Alembic commands ###
