"""league_model_fix

Revision ID: 07242aeb9e5e
Revises: 59e623740d2d
Create Date: 2024-01-20 15:20:50.285586

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '07242aeb9e5e'
down_revision: Union[str, None] = '59e623740d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('started', sa.Boolean(), nullable=True))
    op.alter_column('leagues', 'pd_link',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('leagues', 'tier',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('leagues', 'ended',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leagues', 'ended',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('leagues', 'tier',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('leagues', 'pd_link',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('leagues', 'started')
    # ### end Alembic commands ###
