"""view_creation

Revision ID: 08be681abc50
Revises: 9af85f5e8b63
Create Date: 2024-02-05 16:08:17.516192

"""
from typing import Sequence, Union

from alembic import op
from sqlmodel import text
from sqlmodel.orm.session import Session


# revision identifiers, used by Alembic.
revision: str = '08be681abc50'
down_revision: Union[str, None] = '9af85f5e8b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""
CREATE VIEW performance_view AS
SELECT
  heroes.name as hero_name,
  heroes.id as hero_id,
  positions.name as position_name,
  positions.id as position_id,
  players.id as player_id,
  players.nickname as player_nickname,
  players.official_name as player_official_name,
  teams.id as team_id,
  teams.name as team_id,
  teams.tag as team_id,
  games.*,
  player_games_data.*,
  performance_data_categories.*,
  performance_data_types.*,
  performance_data_descriptions.*,
  performance_windows_data.*,
  performance_totals_data.*
FROM
  games, 
  player_games_data, 
  performance_data_types, 
  performance_data_descriptions, 
  performance_windows_data, 
  performance_totals_data,
  heroes,
  positions,
  players,
  teams
  
  INNER JOIN performance_data_categories.id = performance_data_types.data_category_id
  INNER JOIN performance_data_descriptions.data_type_id = performance_data_types.id
  LEFT JOIN performance_data_descriptions.comparison_id = comparison_types.id
  INNER JOIN performance_windows_data.data_info_id = performance_data_descriptions.id
  INNER JOIN performance_totals_data.data_info_id = performance_data_descriptions.id
  INNER JOIN games_performance.id = performance_windows_data.game_performance_id
  INNER JOIN games_performance.id = performance_totals_data.game_performance_id
  INNER JOIN player_games_data.performance_id = games_performance.id
  INNER JOIN player_games_data.game_id = games.id
  INNER JOIN player_games_data.team_id = teams.id
  INNER JOIN player_games_data.player_id = players.id
  INNER JOIN player_games_data.position_id = positions.id
  INNER JOIN player_games_data.hero_id = heroes.id
WHERE
  performance_data_descriptions.is_aggregation = false WITH CASCADED CHECK OPTION;
"""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""DROP VIEW IF EXISTS performance_view""")
        )
    # ### end Alembic commands ###
