"""index

Revision ID: 0a87db3b7b5e
Revises: f530c5636d82
Create Date: 2024-04-23 03:31:30.273248

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a87db3b7b5e'
down_revision: Union[str, None] = 'f530c5636d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_games_dire_game_data_id'), 'games', ['dire_game_data_id'], unique=False)
    op.create_index(op.f('ix_games_sent_game_data_id'), 'games', ['sent_game_data_id'], unique=False)
    op.alter_column('performance_totals_data', 'kills_per_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'kills_per_min',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_games_sent_game_data_id'), table_name='games')
    op.drop_index(op.f('ix_games_dire_game_data_id'), table_name='games')
    # ### end Alembic commands ###
