"""by_team_id_for_aggregation

Revision ID: 1b30cf843249
Revises: 51628b363f79
Create Date: 2024-02-21 02:12:30.881771

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1b30cf843249'
down_revision: Union[str, None] = '51628b363f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_aggregation_types', sa.Column('by_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_aggregation_types', 'teams', ['by_team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_aggregation_types', type_='foreignkey')
    op.drop_column('data_aggregation_types', 'by_team_id')
    # ### end Alembic commands ###
