"""field fix

Revision ID: 1eca8a6a36ba
Revises: 934feb893faa
Create Date: 2025-08-10 21:25:36.402963

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eca8a6a36ba'
down_revision: Union[str, None] = '934feb893faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lop_short_data_momentum', 'last_pick_win')
    op.drop_column('lop_short_data_momentum', 'win_sent')
    op.drop_column('lop_short_data_momentum', 'win_dire')
    op.drop_column('lop_short_data_momentum', 'net_worth')
    op.drop_column('lop_short_data_momentum', 'hero_kills')
    op.drop_column('lop_short_data_momentum', 'last_hits')
    op.drop_column('lop_short_data_momentum', 'kpm')
    op.drop_column('lop_short_data_momentum', 'duration')
    op.drop_column('lop_short_data_momentum', 'first_pick_win')
    op.drop_column('lop_short_data_momentum', 'cores_networth_at_15')
    op.drop_column('lop_short_data_momentum', 'supports_networth_at_15')
    op.drop_column('lop_short_data_momentum', 'cores_level_at_15')
    op.drop_column('lop_short_data_momentum', 'supports_level_at_15')
    op.drop_column('lop_short_data_momentum', 'matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
