"""windows_performance_compression_2

Revision ID: 1f5881e47fc7
Revises: 8432d29a5850
Create Date: 2024-08-12 22:42:23.774796

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
from sqlmodel import text
from sqlmodel.orm.session import Session

# revision identifiers, used by Alembic.
revision: str = '1f5881e47fc7'
down_revision: Union[str, None] = '8432d29a5850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        # setting null to 0 columns
        print('Setting null to l* values')
        sqlmodel_session.execute(
            text("""UPDATE performance_windows_data 
                    SET 
                    l2 = NULL,
                    l4 = NULL,
                    l6 = NULL,
                    l8 = NULL,
                    l10 = NULL,
                    ltotal = NULL
                    WHERE l_empty_mask IS NOT NULL
                    """),
        )

        print('Setting null to g* values')
        sqlmodel_session.execute(
            text("""UPDATE performance_windows_data
                    g15 = NULL,
                    g30 = NULL,
                    g45 = NULL,
                    g60 = NULL,
                    g60plus = NULL,
                    gtotal = NULL,
                    WHERE g_empty_mask IS NOT NULL
                    """),
        )


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
