"""graph

Revision ID: 25e56a017b43
Revises: 3ef26750b526
Create Date: 2025-07-14 12:34:16.332574

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e56a017b43'
down_revision: Union[str, None] = '3ef26750b526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_performance_graphs',
    sa.Column('xp_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp_3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp_4', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp_5', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xp_game', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gold_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gold_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gold_3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gold_4', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gold_5', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gold_game', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_performance_graphs')
    # ### end Alembic commands ###
