"""building data

Revision ID: 2ccd4e3b93f3
Revises: 80c8cb1b0f4b
Create Date: 2025-07-09 06:32:52.256709

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccd4e3b93f3'
down_revision: Union[str, None] = '80c8cb1b0f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings_data', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buildings_data', 'performances', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_games_sent_building_status_id_buildings_data', 'games', type_='foreignkey')
    op.drop_constraint('fk_games_dire_building_status_id_buildings_data', 'games', type_='foreignkey')
    op.drop_column('games', 'sent_building_status_id')
    op.drop_column('games', 'dire_building_status_id')
    op.add_column('performance_totals_data', sa.Column('win_with_megas', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('lose_with_megas', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('win_against_megas', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('lose_against_megas', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_totals_data', 'lose_against_megas')
    op.drop_column('performance_totals_data', 'win_against_megas')
    op.drop_column('performance_totals_data', 'lose_with_megas')
    op.drop_column('performance_totals_data', 'win_with_megas')
    op.add_column('games', sa.Column('dire_building_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('sent_building_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_games_dire_building_status_id_buildings_data', 'games', 'buildings_data', ['dire_building_status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_games_sent_building_status_id_buildings_data', 'games', 'buildings_data', ['sent_building_status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'buildings_data', type_='foreignkey')
    op.drop_column('buildings_data', 'game_id')
    # ### end Alembic commands ###
