"""rename_to_basic

Revision ID: 2dfcb08644b7
Revises: b45a9bbcf8f3
Create Date: 2024-02-26 01:20:55.812827

"""
from sqlmodel.orm.session import Session
from typing import Sequence, Union

from sqlmodel import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfcb08644b7'
down_revision: Union[str, None] = 'b45a9bbcf8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""DROP VIEW IF EXISTS performance_window_view""")
        )
        sqlmodel_session.execute(
            text("""DROP VIEW IF EXISTS performance_total_view""")
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_types', sa.Column('basic', sa.Boolean(), nullable=True))
    op.drop_column('comparison_types', 'general')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_types', sa.Column('general', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('comparison_types', 'basic')
    # ### end Alembic commands ###
