"""bool_index

Revision ID: 30d39de6af74
Revises: 4282bd11126e
Create Date: 2025-06-08 00:42:28.621819

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d39de6af74'
down_revision: Union[str, None] = '4282bd11126e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comparison_types_is_flat'), 'comparison_types', ['is_flat'], unique=False)
    op.create_index(op.f('ix_cross_comparison_types_type_id'), 'cross_comparison_types', ['type_id'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_type_id'), 'data_aggregation_types', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_aggregation_types_type_id'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_cross_comparison_types_type_id'), table_name='cross_comparison_types')
    op.drop_index(op.f('ix_comparison_types_is_flat'), table_name='comparison_types')
    # ### end Alembic commands ###
