"""change_fields

Revision ID: 32335e971d63
Revises: f5530a5df7a4
Create Date: 2025-07-02 07:25:35.371084

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32335e971d63'
down_revision: Union[str, None] = 'f5530a5df7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_totals_data', 'lane_efficiency_pct')
    op.alter_column('sides_performance_data', 'hero_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sides_performance_data', 'hero_kills',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('performance_totals_data', sa.Column('lane_efficiency_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
