"""updated at and new fields

Revision ID: 32aeeb77a2bb
Revises: 5a13d0d8108d
Create Date: 2025-08-07 22:49:12.618062

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32aeeb77a2bb'
down_revision: Union[str, None] = '5a13d0d8108d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lop_short_data',
    sa.Column('first_pick_win', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('last_pick_win', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('win_sent', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('win_dire', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hero_kills', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('last_hits', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('kpm', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('cores_networth_at_15', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('supports_networth_at_15', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('cores_level_at_15', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('supports_level_at_15', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lop_short_data_league_id'), 'lop_short_data', ['league_id'], unique=False)
    op.create_index(op.f('ix_lop_short_data_patch_id'), 'lop_short_data', ['patch_id'], unique=False)
    op.create_table('lop_short_data_momentum',
    sa.Column('first_pick_win', sa.Boolean(), nullable=True),
    sa.Column('last_pick_win', sa.Boolean(), nullable=True),
    sa.Column('win_sent', sa.Boolean(), nullable=True),
    sa.Column('win_dire', sa.Boolean(), nullable=True),
    sa.Column('net_worth', sa.Boolean(), nullable=True),
    sa.Column('hero_kills', sa.Boolean(), nullable=True),
    sa.Column('last_hits', sa.Boolean(), nullable=True),
    sa.Column('kpm', sa.Boolean(), nullable=True),
    sa.Column('matches', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Boolean(), nullable=True),
    sa.Column('cores_networth_at_15', sa.Boolean(), nullable=True),
    sa.Column('supports_networth_at_15', sa.Boolean(), nullable=True),
    sa.Column('cores_level_at_15', sa.Boolean(), nullable=True),
    sa.Column('supports_level_at_15', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('compared_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['lop_short_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lop_short_data_momentum_data_id'), 'lop_short_data_momentum', ['data_id'], unique=False)
    op.drop_index('ix_lop_short_datas_league_id', table_name='lop_short_datas')
    op.drop_index('ix_lop_short_datas_patch_id', table_name='lop_short_datas')
    op.drop_table('lop_short_datas')
    op.alter_column('games', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'patch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('leagues', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('patches', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'updated_at')
    op.drop_column('leagues', 'updated_at')
    op.alter_column('games', 'patch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('lop_short_datas',
    sa.Column('first_pick_win', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('last_pick_win', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('win_sent', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('win_dire', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_worth', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('hero_kills', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('last_hits', sa.NUMERIC(precision=5, scale=1), autoincrement=False, nullable=False),
    sa.Column('kpm', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('matches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cores_networth_at_15', sa.NUMERIC(precision=7, scale=1), autoincrement=False, nullable=False),
    sa.Column('supports_networth_at_15', sa.NUMERIC(precision=7, scale=1), autoincrement=False, nullable=False),
    sa.Column('cores_level_at_15', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('supports_level_at_15', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name='fk_lop_short_datas_league_id_leagues'),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], name='fk_lop_short_datas_patch_id_patches'),
    sa.PrimaryKeyConstraint('id', name='pk_lop_short_datas')
    )
    op.create_index('ix_lop_short_datas_patch_id', 'lop_short_datas', ['patch_id'], unique=False)
    op.create_index('ix_lop_short_datas_league_id', 'lop_short_datas', ['league_id'], unique=False)
    op.drop_index(op.f('ix_lop_short_data_momentum_data_id'), table_name='lop_short_data_momentum')
    op.drop_table('lop_short_data_momentum')
    op.drop_index(op.f('ix_lop_short_data_patch_id'), table_name='lop_short_data')
    op.drop_index(op.f('ix_lop_short_data_league_id'), table_name='lop_short_data')
    op.drop_table('lop_short_data')
    # ### end Alembic commands ###
