"""category_description

Revision ID: 35925d1eb184
Revises: 80c2a04b15a3
Create Date: 2024-05-12 12:58:49.299236

"""
from typing import Sequence, Union
from sqlmodel.orm.session import Session

from base_data_creation import update_category_data
from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35925d1eb184'
down_revision: Union[str, None] = '80c2a04b15a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('performance_data_categories', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('performance_data_categories', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        update_category_data(sqlmodel_session)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_data_categories', 'description')    # ### end Alembic commands ###
    op.drop_column('performance_data_categories', 'label')    # ### end Alembic commands ###
    # ### end Alembic commands ###

