"""script

Revision ID: 360a660319ab
Revises: cc3d8fc4bdb0
Create Date: 2025-04-20 23:57:05.937063

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360a660319ab'
down_revision: Union[str, None] = 'cc3d8fc4bdb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from sqlmodel.orm.session import Session

from alembic import op
import sqlalchemy as sa

from scripts.populate_all import populate_all


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        populate_all(sqlmodel_session)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
