"""game_length_field

Revision ID: 363a3fd70fd3
Revises: e55b20e4924c
Create Date: 2025-06-27 23:43:45.816406

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363a3fd70fd3'
down_revision: Union[str, None] = 'e55b20e4924c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_totals_data', 'duration')
    # ### end Alembic commands ###
