"""approximate_pos

Revision ID: 3a5491d5b572
Revises: 048f5472067b
Create Date: 2024-03-14 15:39:55.623814

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5491d5b572'
down_revision: Union[str, None] = '048f5472067b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approximated_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.account_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('data_aggregation_types', sa.Column('pos_player_cross', sa.Boolean(), nullable=True))
    op.add_column('data_aggregation_types', sa.Column('pos_hero_cross', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_aggregation_types', 'pos_hero_cross')
    op.drop_column('data_aggregation_types', 'pos_player_cross')
    op.drop_table('approximated_positions')
    # ### end Alembic commands ###
