"""patch_id and index

Revision ID: 3b17e7a73a8a
Revises: 360a660319ab
Create Date: 2025-04-30 01:52:17.763985

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b17e7a73a8a'
down_revision: Union[str, None] = '360a660319ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_by_team_types_league_id', table_name='by_team_types')
    op.drop_index('ix_comparison_types_basic', table_name='comparison_types')
    op.drop_index('ix_comparison_types_is_flat', table_name='comparison_types')
    op.add_column('cross_comparison_types', sa.Column('patch_id', sa.Integer(), nullable=True))
    op.drop_index('ix_cross_comparison_types_league_id', table_name='cross_comparison_types')
    op.create_foreign_key(None, 'cross_comparison_types', 'patches', ['patch_id'], ['id'])
    op.drop_index('ix_data_aggregation_types_league_id', table_name='data_aggregation_types')
    op.drop_index('ix_data_aggregation_types_patch_id', table_name='data_aggregation_types')
    op.create_index(op.f('ix_performances_type_id'), 'performances', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performances_type_id'), table_name='performances')
    op.create_index('ix_data_aggregation_types_patch_id', 'data_aggregation_types', ['patch_id'], unique=False)
    op.create_index('ix_data_aggregation_types_league_id', 'data_aggregation_types', ['league_id'], unique=False)
    op.drop_constraint(None, 'cross_comparison_types', type_='foreignkey')
    op.create_index('ix_cross_comparison_types_league_id', 'cross_comparison_types', ['league_id'], unique=False)
    op.drop_column('cross_comparison_types', 'patch_id')
    op.create_index('ix_comparison_types_is_flat', 'comparison_types', ['is_flat'], unique=False)
    op.create_index('ix_comparison_types_basic', 'comparison_types', ['basic'], unique=False)
    op.create_index('ix_by_team_types_league_id', 'by_team_types', ['league_id'], unique=False)
    # ### end Alembic commands ###
