"""team_id

Revision ID: 3ef26750b526
Revises: 697999e0c8db
Create Date: 2025-07-12 08:22:43.510477

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef26750b526'
down_revision: Union[str, None] = '697999e0c8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approximated_positions', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'approximated_positions', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approximated_positions', type_='foreignkey')
    op.drop_column('approximated_positions', 'team_id')
    # ### end Alembic commands ###
