"""script

Revision ID: 3f3037978934
Revises: 7ffa267a851b
Create Date: 2025-04-06 23:29:30.279813

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes
from sqlmodel.orm.session import Session

from alembic import op
import sqlalchemy as sa

from scripts.populate_all import populate_all

# revision identifiers, used by Alembic.
revision: str = '3f3037978934'
down_revision: Union[str, None] = '7ffa267a851b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        populate_all(sqlmodel_session)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
