"""side

Revision ID: 4282bd11126e
Revises: 726221ac25d6
Create Date: 2025-06-05 01:45:00.061329

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4282bd11126e'
down_revision: Union[str, None] = '726221ac25d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('by_team_types', sa.Column('is_dire', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_by_team_types_is_dire'), 'by_team_types', ['is_dire'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_by_team_types_is_dire'), table_name='by_team_types')
    op.drop_column('by_team_types', 'is_dire')
    # ### end Alembic commands ###
