"""cps aggregation fields

Revision ID: 43ed994de140
Revises: f1dc12453689
Create Date: 2024-03-10 23:05:40.025226

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel import text
from sqlmodel.orm.session import Session


# revision identifiers, used by Alembic.
revision: str = '43ed994de140'
down_revision: Union[str, None] = 'f1dc12453689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_aggregation_types', sa.Column('player_cross_cps_id', sa.Integer(), nullable=True))
    op.add_column('data_aggregation_types', sa.Column('hero_cross_cps_id', sa.Integer(), nullable=True))
    op.add_column('data_aggregation_types', sa.Column('position_cross_cps_id', sa.Integer(), nullable=True))
    op.add_column('data_aggregation_types', sa.Column('cross_comparison', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'data_aggregation_types', 'players', ['player_cross_cps_id'], ['account_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'data_aggregation_types', 'heroes', ['hero_cross_cps_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'data_aggregation_types', 'positions', ['position_cross_cps_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""UPDATE data_aggregation_types SET cross_comparison = false""")
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_aggregation_types', type_='foreignkey')
    op.drop_constraint(None, 'data_aggregation_types', type_='foreignkey')
    op.drop_constraint(None, 'data_aggregation_types', type_='foreignkey')
    op.drop_column('data_aggregation_types', 'cross_comparison')
    op.drop_column('data_aggregation_types', 'position_cross_cps_id')
    op.drop_column('data_aggregation_types', 'hero_cross_cps_id')
    op.drop_column('data_aggregation_types', 'player_cross_cps_id')
    # ### end Alembic commands ###
