"""totals_to_floats

Revision ID: 44b213778251
Revises: 952cab93ef58
Create Date: 2024-03-23 02:35:35.222388

"""
from typing import Sequence, Union

from sqlmodel import text
from sqlmodel.orm.session import Session

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b213778251'
down_revision: Union[str, None] = '952cab93ef58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'total_gold',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'total_xp',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'neutral_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'tower_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'courier_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'lane_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'hero_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'observer_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'sentry_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'roshan_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'runes_picked_up',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'ancient_kills',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'buyback_count',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'observer_uses',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'sentry_uses',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('performance_totals_data', 'lane_efficiency_pct',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'lane_efficiency_pct',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'sentry_uses',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'observer_uses',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'buyback_count',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'ancient_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'runes_picked_up',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'roshan_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'sentry_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'observer_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'hero_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'lane_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'courier_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'tower_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'neutral_kills',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'total_xp',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('performance_totals_data', 'total_gold',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
