"""fix_kda_and_kills_rows_in_ptd

Revision ID: 4680381ebde5
Revises: 48fe6a427b3b
Create Date: 2024-01-25 14:26:00.406052

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4680381ebde5'
down_revision: Union[str, None] = '48fe6a427b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'kills_per_min',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_nullable=False)
    op.alter_column('performance_totals_data', 'kda',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=5, scale=2),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'kda',
                    existing_type=sa.Numeric(precision=5, scale=2),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('performance_totals_data', 'kills_per_min',
                    existing_type=sa.Numeric(precision=10, scale=2),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
