"""percent_field

Revision ID: 47b4faf4efc9
Revises: 680c68cb42c4
Create Date: 2024-01-31 16:26:25.243717

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '47b4faf4efc9'
down_revision: Union[str, None] = '680c68cb42c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_types', sa.Column('percent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison_types', 'percent')
    # ### end Alembic commands ###
