"""add_official_name_to_player

Revision ID: 48fe6a427b3b
Revises: ba6235db00a1
Create Date: 2024-01-25 13:50:18.505559

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.orm.session import Session

from base_data_creation import set_official_name_to_true


# revision identifiers, used by Alembic.
revision: str = '48fe6a427b3b'
down_revision: Union[str, None] = 'ba6235db00a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('official_name', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        set_official_name_to_true(sqlmodel_session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'official_name')
    # ### end Alembic commands ###
