"""patch_field

Revision ID: 4ce87470d81e
Revises: bb664ec13778
Create Date: 2025-06-29 02:40:57.054790

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce87470d81e'
down_revision: Union[str, None] = 'bb664ec13778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('should_be_processed_today', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'should_be_processed_today')
    # ### end Alembic commands ###
