"""fix_4

Revision ID: 4d6830bf8b83
Revises: 9757e14f8789
Create Date: 2025-05-17 16:41:57.115251

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6830bf8b83'
down_revision: Union[str, None] = '9757e14f8789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'net_worth',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'net_worth',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
