"""create facets

Revision ID: 4f02779ae5c2
Revises: 35925d1eb184
Create Date: 2024-06-17 22:00:50.265265

"""
import os
import pathlib
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union

from alembic import op
from sqlmodel.orm.session import Session
from base_data_creation import update_facets

# revision identifiers, used by Alembic.
revision: str = '4f02779ae5c2'
down_revision: Union[str, None] = '35925d1eb184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('cdota_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gradient_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facets_cdota_name'), 'facets', ['cdota_name'], unique=True)
    op.create_index(op.f('ix_facets_hero_id'), 'facets', ['hero_id'], unique=False)

    op.add_column('players_game_data', sa.Column('facet_id', sa.Integer(), nullable=True))

    op.create_foreign_key(None, 'players_game_data', 'facets', ['facet_id'], ['id'])
    op.add_column('teams', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        full_path = os.path.join(pathlib.Path(os.getcwd()), 'data/hero_abilities_facets_v1.json')
        update_facets(sqlmodel_session, pathlib.Path(full_path))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo_url')
    op.drop_constraint(None, 'players_game_data', type_='foreignkey')
    op.drop_column('players_game_data', 'facet_id')

    op.drop_index(op.f('ix_facets_hero_id'), table_name='facets')
    op.drop_index(op.f('ix_facets_cdota_name'), table_name='facets')
    op.drop_table('facets')
    # ### end Alembic commands ###
