"""by_win

Revision ID: 59018b3b2698
Revises: f57a2e451f95
Create Date: 2024-02-20 00:53:57.798568

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '59018b3b2698'
down_revision: Union[str, None] = 'f57a2e451f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_aggregation_types', sa.Column('by_win', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_aggregation_types', 'by_win')
    # ### end Alembic commands ###
