"""create_base_data

Revision ID: 59e623740d2d
Revises: a24fa64db7cf
Create Date: 2024-01-17 16:21:52.906428

"""
from typing import Sequence, Union

from alembic import op
from sqlmodel.orm.session import Session

from base_data_creation import create_buildings, delete_buildings
from base_data_creation import create_heroes, delete_heroes
from base_data_creation import create_performance_data_tags, delete_performance_data_tags
from base_data_creation import create_positions, delete_positions

# revision identifiers, used by Alembic.
revision: str = '59e623740d2d'
down_revision: Union[str, None] = 'c3b1ab7d2f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        create_performance_data_tags(sqlmodel_session)
        create_buildings(sqlmodel_session)
        create_heroes(sqlmodel_session)
        create_positions(sqlmodel_session)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        delete_performance_data_tags(sqlmodel_session)
        delete_buildings(sqlmodel_session)
        delete_heroes(sqlmodel_session)
        delete_positions(sqlmodel_session)
    # ### end Alembic commands ###
