"""delete indexes

Revision ID: 5a13d0d8108d
Revises: b05f215ef2a2
Create Date: 2025-07-31 14:08:21.550378

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a13d0d8108d'
down_revision: Union[str, None] = 'b05f215ef2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_by_team_types_is_dire', table_name='by_team_types')
    op.drop_index('ix_by_team_types_is_flat', table_name='by_team_types')
    op.drop_index('ix_comparison_types_is_flat', table_name='comparison_types')
    op.drop_index('ix_heroes_name', table_name='heroes')
    op.create_unique_constraint(None, 'heroes', ['name'])
    op.drop_index('ix_leagues_id', table_name='leagues')
    op.drop_index('ix_sides_performance_data_id', table_name='sides_performance_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sides_performance_data_id', 'sides_performance_data', ['id'], unique=False)
    op.create_index('ix_leagues_id', 'leagues', ['id'], unique=False)
    op.drop_constraint(None, 'heroes', type_='unique')
    op.create_index('ix_heroes_name', 'heroes', ['name'], unique=True)
    op.create_index('ix_comparison_types_is_flat', 'comparison_types', ['is_flat'], unique=False)
    op.create_index('ix_by_team_types_is_flat', 'by_team_types', ['is_flat'], unique=False)
    op.create_index('ix_by_team_types_is_dire', 'by_team_types', ['is_dire'], unique=False)
    # ### end Alembic commands ###
