"""indexes

Revision ID: 5f539bfac290
Revises: 85714d267da8
Create Date: 2025-09-06 21:20:45.846782

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f539bfac290'
down_revision: Union[str, None] = '85714d267da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_performance_windows_data_performance_id'), 'performance_windows_data', ['performance_id'], unique=False)
    op.create_index(op.f('ix_players_game_data_facet_id'), 'players_game_data', ['facet_id'], unique=False)
    op.create_index(op.f('ix_players_game_data_hero_id'), 'players_game_data', ['hero_id'], unique=False)
    op.create_index(op.f('ix_players_game_data_player_id'), 'players_game_data', ['player_id'], unique=False)
    op.create_index(op.f('ix_players_game_data_position_id'), 'players_game_data', ['position_id'], unique=False)
    op.create_index(op.f('ix_players_game_data_team_id'), 'players_game_data', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_game_data_team_id'), table_name='players_game_data')
    op.drop_index(op.f('ix_players_game_data_position_id'), table_name='players_game_data')
    op.drop_index(op.f('ix_players_game_data_player_id'), table_name='players_game_data')
    op.drop_index(op.f('ix_players_game_data_hero_id'), table_name='players_game_data')
    op.drop_index(op.f('ix_players_game_data_facet_id'), table_name='players_game_data')
    op.drop_index(op.f('ix_performance_windows_data_performance_id'), table_name='performance_windows_data')
    # ### end Alembic commands ###
