"""field fix

Revision ID: 66add17800b0
Revises: 4d6830bf8b83
Create Date: 2025-05-18 22:24:47.369505

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66add17800b0'
down_revision: Union[str, None] = '4d6830bf8b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comparison_types', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('comparison_types_id_seq'::regclass)"))
    op.drop_index('ix_comparison_types_id', table_name='comparison_types')
    op.add_column('performance_windows_table', sa.Column('ltotal_max', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('performance_windows_table', sa.Column('ltotal_min', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('performance_windows_table', sa.Column('gtotal_max', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('performance_windows_table', sa.Column('gtotal_min', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('performance_windows_table', 'ltotal')
    op.drop_column('performance_windows_table', 'gtotal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_windows_table', sa.Column('gtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_windows_table', sa.Column('ltotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('performance_windows_table', 'gtotal_min')
    op.drop_column('performance_windows_table', 'gtotal_max')
    op.drop_column('performance_windows_table', 'ltotal_min')
    op.drop_column('performance_windows_table', 'ltotal_max')
    op.create_index('ix_comparison_types_id', 'comparison_types', ['id'], unique=False)
    op.alter_column('comparison_types', 'id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('comparison_types_id_seq'::regclass)"))
    # ### end Alembic commands ###
