"""remove_nickname_from_PGD

Revision ID: 680c68cb42c4
Revises: 4680381ebde5
Create Date: 2024-01-25 15:30:20.364354

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '680c68cb42c4'
down_revision: Union[str, None] = '4680381ebde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_games_data', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_games_data', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
