"""og position

Revision ID: 697999e0c8db
Revises: 075b409347f8
Create Date: 2025-07-11 11:12:00.054636

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697999e0c8db'
down_revision: Union[str, None] = '075b409347f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_game_data', sa.Column('original_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players_game_data', 'original_position')
    # ### end Alembic commands ###
