"""bigint_fields

Revision ID: 6d77b63ed85c
Revises: 47b4faf4efc9
Create Date: 2024-01-31 16:41:39.260940

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6d77b63ed85c'
down_revision: Union[str, None] = '47b4faf4efc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'match_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.alter_column('games', 'game_start_time',
                    existing_type=sa.INTEGER(),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.drop_index('ix_games_match_id', table_name='games')
    op.create_unique_constraint(None, 'games', ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.create_index('ix_games_match_id', 'games', ['match_id'], unique=True)
    op.alter_column('games', 'game_start_time',
                    existing_type=sa.BIGINT(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('games', 'match_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    # ### end Alembic commands ###
