"""field fix

Revision ID: 70215c374af0
Revises: 1eca8a6a36ba
Create Date: 2025-08-10 21:39:34.629415

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70215c374af0'
down_revision: Union[str, None] = '1eca8a6a36ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lop_short_data_momentum', sa.Column('first_pick_win', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('last_pick_win', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('win_sent', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('win_dire', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('net_worth', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('hero_kills', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('last_hits', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('kpm', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('cores_networth_at_15', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('supports_networth_at_15', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('cores_level_at_15', sa.Numeric(), nullable=True))
    op.add_column('lop_short_data_momentum', sa.Column('supports_level_at_15', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lop_short_data_momentum', 'supports_level_at_15')
    op.drop_column('lop_short_data_momentum', 'cores_level_at_15')
    op.drop_column('lop_short_data_momentum', 'supports_networth_at_15')
    op.drop_column('lop_short_data_momentum', 'cores_networth_at_15')
    op.drop_column('lop_short_data_momentum', 'duration')
    op.drop_column('lop_short_data_momentum', 'kpm')
    op.drop_column('lop_short_data_momentum', 'last_hits')
    op.drop_column('lop_short_data_momentum', 'hero_kills')
    op.drop_column('lop_short_data_momentum', 'net_worth')
    op.drop_column('lop_short_data_momentum', 'win_dire')
    op.drop_column('lop_short_data_momentum', 'win_sent')
    op.drop_column('lop_short_data_momentum', 'last_pick_win')
    op.drop_column('lop_short_data_momentum', 'first_pick_win')
    # ### end Alembic commands ###
