"""patch_league_indexs

Revision ID: 77ba22f39f6a
Revises: 30d39de6af74
Create Date: 2025-06-08 01:27:07.553577

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ba22f39f6a'
down_revision: Union[str, None] = '30d39de6af74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_by_team_types_league_id'), 'by_team_types', ['league_id'], unique=False)
    op.create_index(op.f('ix_by_team_types_patch_id'), 'by_team_types', ['patch_id'], unique=False)
    op.create_index(op.f('ix_cross_comparison_types_league_id'), 'cross_comparison_types', ['league_id'], unique=False)
    op.create_index(op.f('ix_cross_comparison_types_patch_id'), 'cross_comparison_types', ['patch_id'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_league_id'), 'data_aggregation_types', ['league_id'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_patch_id'), 'data_aggregation_types', ['patch_id'], unique=False)
    op.add_column('performances', sa.Column('outdated', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_performances_outdated'), 'performances', ['outdated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performances_outdated'), table_name='performances')
    op.drop_column('performances', 'outdated')
    op.drop_index(op.f('ix_data_aggregation_types_patch_id'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_league_id'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_cross_comparison_types_patch_id'), table_name='cross_comparison_types')
    op.drop_index(op.f('ix_cross_comparison_types_league_id'), table_name='cross_comparison_types')
    op.drop_index(op.f('ix_by_team_types_patch_id'), table_name='by_team_types')
    op.drop_index(op.f('ix_by_team_types_league_id'), table_name='by_team_types')
    # ### end Alembic commands ###
