"""advantage fields

Revision ID: 7d31b448243f
Revises: 1c43ff1abc6f
Create Date: 2025-07-28 13:50:58.146457

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d31b448243f'
down_revision: Union[str, None] = 'fd455316f124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lop_short_datas',
    sa.Column('first_pick_win', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('last_pick_win', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('win_sent', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('win_dire', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('hero_kills', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('last_hits', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('kpm', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('cores_networth_at_15', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('supports_networth_at_15', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('cores_level_at_15', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('supports_level_at_15', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lop_short_datas_league_id'), 'lop_short_datas', ['league_id'], unique=False)
    op.create_index(op.f('ix_lop_short_datas_patch_id'), 'lop_short_datas', ['patch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lop_short_datas_patch_id'), table_name='lop_short_datas')
    op.drop_index(op.f('ix_lop_short_datas_league_id'), table_name='lop_short_datas')
    op.drop_table('lop_short_datas')
    # ### end Alembic commands ###
