"""add short names

Revision ID: 80c2a04b15a3
Revises: 0a87db3b7b5e
Create Date: 2024-05-09 12:50:47.782841

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c2a04b15a3'
down_revision: Union[str, None] = '0a87db3b7b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_types', sa.Column('cps_name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comparison_types', sa.Column('cpd_name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comparison_types', sa.Column('cps_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comparison_types', sa.Column('cpd_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('players_game_data', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('players_game_data', sa.Column('name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players_game_data', 'name_short')
    op.drop_column('players_game_data', 'name')
    op.drop_column('comparison_types', 'cpd_name')
    op.drop_column('comparison_types', 'cps_name')
    op.drop_column('comparison_types', 'cpd_name_short')
    op.drop_column('comparison_types', 'cps_name_short')
    # ### end Alembic commands ###
