"""field_fix

Revision ID: 80c8cb1b0f4b
Revises: aa7f5425da47
Create Date: 2025-07-07 10:56:01.013578

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c8cb1b0f4b'
down_revision: Union[str, None] = 'aa7f5425da47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sides_performance_data', 'hero_kills',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('sides_performance_data', 'kills_per_min',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sides_performance_data', 'kills_per_min',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('sides_performance_data', 'hero_kills',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
