"""duration win lose

Revision ID: 85714d267da8
Revises: 70215c374af0
Create Date: 2025-08-29 18:15:06.171177

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85714d267da8'
down_revision: Union[str, None] = '70215c374af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('duration_win', sa.Integer(), nullable=True))
    op.add_column('performance_totals_data', sa.Column('duration_lose', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_totals_data', 'duration_lose')
    op.drop_column('performance_totals_data', 'duration_win')
    # ### end Alembic commands ###
