"""init

Revision ID: 8b73f5d7647e
Revises: 
Create Date: 2023-11-06 04:02:28.917385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b73f5d7647e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('xpm', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Integer(), nullable=False),
    sa.Column('kpm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hero_damage', sa.Integer(), nullable=False),
    sa.Column('team_fight_participation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('creeps_stacked', sa.Integer(), nullable=False),
    sa.Column('creep_denies', sa.Integer(), nullable=False),
    sa.Column('last_hits', sa.Integer(), nullable=False),
    sa.Column('creep_kills', sa.Integer(), nullable=False),
    sa.Column('neutral_kills', sa.Integer(), nullable=False),
    sa.Column('ancient_kills', sa.Integer(), nullable=False),
    sa.Column('observer_kills', sa.Integer(), nullable=False),
    sa.Column('sentry_kills', sa.Integer(), nullable=False),
    sa.Column('dewards', sa.Integer(), nullable=False),
    sa.Column('net_worth', sa.Integer(), nullable=False),
    sa.Column('gold_spent', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('gpm', sa.Integer(), nullable=False),
    sa.Column('tower_damage', sa.Integer(), nullable=False),
    sa.Column('pings', sa.Integer(), nullable=False),
    sa.Column('apm', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('runes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odota_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odota_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Interval(), nullable=False),
    sa.Column('end_date', sa.Interval(), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameitembackpacklink',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'item_id')
    )
    op.create_table('gameitempurchaselink',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'item_id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('dire', sa.Integer(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=False),
    sa.Column('total_draft_time', sa.Integer(), nullable=False),
    sa.Column('radiant_draft_time', sa.Integer(), nullable=False),
    sa.Column('dire_draft_time', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('game_start_time', sa.Integer(), nullable=False),
    sa.Column('replay_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['dire'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('hero', sa.Integer(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.ForeignKeyConstraint(['hero'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['lane'], ['lane.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    op.drop_table('match')
    op.drop_table('gameitempurchaselink')
    op.drop_table('gameitembackpacklink')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('league')
    op.drop_table('lane')
    op.drop_table('item')
    op.drop_table('hero')
    op.drop_table('game')
    # ### end Alembic commands ###
