"""new fields 5

Revision ID: 92d9e6f7f19f
Revises: 66add17800b0
Create Date: 2025-06-01 21:36:08.073513

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d9e6f7f19f'
down_revision: Union[str, None] = '66add17800b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('first_tower_destroyed_mid', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_destroyed_top', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_destroyed_bot', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lost_mid', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lost_top', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lost_bot', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_win', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_lose', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('last_pick_win', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('last_pick_lose', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('last_pick_hero', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_hero', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lane_destroyed_mid', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lane_destroyed_top', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lane_destroyed_bot', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lane_lost_mid', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lane_lost_top', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_tower_lane_lost_bot', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_barracks_set_destroyed_mid', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_barracks_set_destroyed_top', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_barracks_set_destroyed_bot', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_barracks_set_lost_mid', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_barracks_set_lost_top', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_barracks_set_lost_bot', sa.Numeric(precision=3, scale=2), nullable=True))
    op.drop_column('performance_totals_data', 'first_destroyed_bot')
    op.drop_column('performance_totals_data', 'first_destroyed_top')
    op.drop_column('performance_totals_data', 'first_lost_mid')
    op.drop_column('performance_totals_data', 'first_destroyed_mid')
    op.drop_column('performance_totals_data', 'first_lost_bot')
    op.drop_column('performance_totals_data', 'first_lost_top')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('first_lost_top', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_lost_bot', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_destroyed_mid', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_lost_mid', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_destroyed_top', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_destroyed_bot', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.drop_column('performance_totals_data', 'first_barracks_set_lost_bot')
    op.drop_column('performance_totals_data', 'first_barracks_set_lost_top')
    op.drop_column('performance_totals_data', 'first_barracks_set_lost_mid')
    op.drop_column('performance_totals_data', 'first_barracks_set_destroyed_bot')
    op.drop_column('performance_totals_data', 'first_barracks_set_destroyed_top')
    op.drop_column('performance_totals_data', 'first_barracks_set_destroyed_mid')
    op.drop_column('performance_totals_data', 'first_tower_lane_lost_bot')
    op.drop_column('performance_totals_data', 'first_tower_lane_lost_top')
    op.drop_column('performance_totals_data', 'first_tower_lane_lost_mid')
    op.drop_column('performance_totals_data', 'first_tower_lane_destroyed_bot')
    op.drop_column('performance_totals_data', 'first_tower_lane_destroyed_top')
    op.drop_column('performance_totals_data', 'first_tower_lane_destroyed_mid')
    op.drop_column('performance_totals_data', 'first_pick_hero')
    op.drop_column('performance_totals_data', 'last_pick_hero')
    op.drop_column('performance_totals_data', 'last_pick_lose')
    op.drop_column('performance_totals_data', 'last_pick_win')
    op.drop_column('performance_totals_data', 'first_pick_lose')
    op.drop_column('performance_totals_data', 'first_pick_win')
    op.drop_column('performance_totals_data', 'first_tower_lost_bot')
    op.drop_column('performance_totals_data', 'first_tower_lost_top')
    op.drop_column('performance_totals_data', 'first_tower_lost_mid')
    op.drop_column('performance_totals_data', 'first_tower_destroyed_bot')
    op.drop_column('performance_totals_data', 'first_tower_destroyed_top')
    op.drop_column('performance_totals_data', 'first_tower_destroyed_mid')
    # ### end Alembic commands ###
