"""new field

Revision ID: 934feb893faa
Revises: 32aeeb77a2bb
Create Date: 2025-08-09 20:46:34.573612

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934feb893faa'
down_revision: Union[str, None] = '32aeeb77a2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lop_short_data', sa.Column('partial_comparison', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lop_short_data', 'partial_comparison')
    # ### end Alembic commands ###
