"""additional indexes

Revision ID: 952cab93ef58
Revises: 14552906d445
Create Date: 2024-03-17 03:45:32.475152

"""

from typing import Sequence, Union

from sqlmodel import text
from sqlmodel.orm.session import Session

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '952cab93ef58'
down_revision: Union[str, None] = '14552906d445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comparison_types_basic'), 'comparison_types', ['basic'], unique=False)
    op.create_index(op.f('ix_comparison_types_flat'), 'comparison_types', ['flat'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_by_hero'), 'data_aggregation_types', ['by_hero'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_by_player'), 'data_aggregation_types', ['by_player'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_by_position'), 'data_aggregation_types', ['by_position'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_carry_cross'), 'data_aggregation_types', ['carry_cross'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_league_id'), 'data_aggregation_types', ['league_id'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_mid_cross'), 'data_aggregation_types', ['mid_cross'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_pos_hero_cross'), 'data_aggregation_types', ['pos_hero_cross'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_pos_player_cross'), 'data_aggregation_types', ['pos_player_cross'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_sup_cross'), 'data_aggregation_types', ['sup_cross'], unique=False)
    op.create_index(op.f('ix_games_performance_cross_comparison'), 'games_performance', ['cross_comparison'], unique=False)
    op.create_index(op.f('ix_performance_data_types_is_comparable'), 'performance_data_types', ['is_comparable'], unique=False)
    op.create_index(op.f('ix_performance_totals_data_game_performance_id'), 'performance_totals_data', ['game_performance_id'], unique=False)
    op.create_index(op.f('ix_performance_windows_data_data_type_id'), 'performance_windows_data', ['data_type_id'], unique=False)
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""DROP VIEW IF EXISTS performance_window_view"""),
        )
        sqlmodel_session.execute(
            text("""DROP VIEW IF EXISTS performance_totals_data""")
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_windows_data_data_type_id'), table_name='performance_windows_data')
    op.drop_index(op.f('ix_performance_totals_data_game_performance_id'), table_name='performance_totals_data')
    op.drop_index(op.f('ix_performance_data_types_is_comparable'), table_name='performance_data_types')
    op.drop_index(op.f('ix_games_performance_cross_comparison'), table_name='games_performance')
    op.drop_index(op.f('ix_data_aggregation_types_sup_cross'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_pos_player_cross'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_pos_hero_cross'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_mid_cross'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_league_id'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_carry_cross'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_by_position'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_by_player'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_by_hero'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_comparison_types_flat'), table_name='comparison_types')
    op.drop_index(op.f('ix_comparison_types_basic'), table_name='comparison_types')
    # ### end Alembic commands ###
