"""fix_3

Revision ID: 9757e14f8789
Revises: cdfac9826210
Create Date: 2025-05-17 03:20:17.537328

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9757e14f8789'
down_revision: Union[str, None] = 'cdfac9826210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'level',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'level',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
