"""rank_fix

Revision ID: 9af85f5e8b63
Revises: 6d77b63ed85c
Create Date: 2024-02-01 18:23:23.006764

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9af85f5e8b63'
down_revision: Union[str, None] = '6d77b63ed85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_games_data', 'rank',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_games_data', 'rank',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
