"""building data

Revision ID: 9dfc58d7d602
Revises: d9f2d32e2759
Create Date: 2025-07-09 06:52:56.885056

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfc58d7d602'
down_revision: Union[str, None] = 'd9f2d32e2759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('win_and_opponent_with_megas', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('lose_and_opponent_with_megas', sa.Numeric(precision=3, scale=2), nullable=True))
    op.drop_column('performance_totals_data', 'win_against_megas')
    op.drop_column('performance_totals_data', 'lose_against_megas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('lose_against_megas', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('performance_totals_data', sa.Column('win_against_megas', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.drop_column('performance_totals_data', 'lose_and_opponent_with_megas')
    op.drop_column('performance_totals_data', 'win_and_opponent_with_megas')
    # ### end Alembic commands ###
