"""dates_variables

Revision ID: a5590fcc0f15
Revises: c098e9386e1c
Create Date: 2024-03-08 20:35:30.889608

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5590fcc0f15'
down_revision: Union[str, None] = 'c098e9386e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('last_parsing_date', sa.BIGINT(), nullable=True))
    op.add_column('leagues', sa.Column('last_aggregation_date', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'last_aggregation_date')
    op.drop_column('leagues', 'last_parsing_date')
    # ### end Alembic commands ###
