"""change_field

Revision ID: aa7f5425da47
Revises: bfecf6007f09
Create Date: 2025-07-07 09:04:54.778717

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7f5425da47'
down_revision: Union[str, None] = 'bfecf6007f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('new_game_found_at', sa.DateTime(), nullable=True))
    op.drop_column('leagues', 'since_last_new_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('since_last_new_game', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('leagues', 'new_game_found_at')
    # ### end Alembic commands ###
