"""patch_field2

Revision ID: afba04ad0ea9
Revises: 4ce87470d81e
Create Date: 2025-06-29 03:36:33.601017

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afba04ad0ea9'
down_revision: Union[str, None] = '4ce87470d81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('should_be_processed', sa.Boolean(), nullable=True))
    op.drop_column('patches', 'should_be_processed_today')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('should_be_processed_today', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('patches', 'should_be_processed')
    # ### end Alembic commands ###
