"""advantage fields

Revision ID: b05f215ef2a2
Revises: 7d31b448243f
Create Date: 2025-07-28 18:02:34.143075

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05f215ef2a2'
down_revision: Union[str, None] = '7d31b448243f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lop_short_datas', 'last_hits',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lop_short_datas', 'last_hits',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###
