"""less3

Revision ID: b45a9bbcf8f3
Revises: 1b30cf843249
Create Date: 2024-02-21 15:23:34.911640

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b45a9bbcf8f3'
down_revision: Union[str, None] = '1b30cf843249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_aggregation_types', sa.Column('less3', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_aggregation_types', 'less3')
    # ### end Alembic commands ###
