"""fix

Revision ID: b75f0a38217f
Revises: 729ea122d8ba
Create Date: 2025-05-17 03:07:23.311822

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75f0a38217f'
down_revision: Union[str, None] = '729ea122d8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'lane_efficiency',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=7, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'lane_efficiency',
               existing_type=sa.Numeric(precision=7, scale=4),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
