"""player_model_fix_and_player_team_creation

Revision ID: ba6235db00a1
Revises: eebabf9abf35
Create Date: 2024-01-24 17:09:53.400764

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel.orm.session import Session

from base_data_creation import create_players_and_teams, delete_all_players_and_teams


# revision identifiers, used by Alembic.
revision: str = 'ba6235db00a1'
down_revision: Union[str, None] = 'eebabf9abf35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('account_id', sa.Integer(), nullable=True))
    op.alter_column('players', 'steam_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BIGINT(),
                    nullable=True)
    op.drop_index('ix_players_steam_id', table_name='players')
    op.create_index(op.f('ix_players_account_id'), 'players', ['account_id'], unique=True)
    op.create_unique_constraint(None, 'players', ['steam_id'])
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        delete_all_players_and_teams(sqlmodel_session)
        create_players_and_teams(sqlmodel_session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_index(op.f('ix_players_account_id'), table_name='players')
    op.create_index('ix_players_steam_id', 'players', ['steam_id'], unique=True)
    op.alter_column('players', 'steam_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.drop_column('players', 'account_id')
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        delete_all_players_and_teams(sqlmodel_session)
