"""remove fields league

Revision ID: bb664ec13778
Revises: 363a3fd70fd3
Create Date: 2025-06-29 02:32:55.492024

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb664ec13778'
down_revision: Union[str, None] = '363a3fd70fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('since_last_new_game', sa.Integer(), nullable=True))
    op.add_column('leagues', sa.Column('waiting_for_ccomp', sa.Boolean(), nullable=True))
    op.add_column('leagues', sa.Column('waiting_for_agg', sa.Boolean(), nullable=True))
    op.drop_column('leagues', 'last_parsing_date')
    op.drop_column('leagues', 'fully_aggregated')
    op.drop_column('leagues', 'fully_parsed')
    op.drop_column('leagues', 'parsed_before')
    op.drop_column('leagues', 'last_aggregation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('last_aggregation_date', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('parsed_before', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('fully_parsed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('leagues', sa.Column('fully_aggregated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('last_parsing_date', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('leagues', 'waiting_for_agg')
    op.drop_column('leagues', 'waiting_for_ccomp')
    op.drop_column('leagues', 'since_last_new_game')
    # ### end Alembic commands ###
