"""change_fields

Revision ID: bfecf6007f09
Revises: 32335e971d63
Create Date: 2025-07-06 05:32:58.913578

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfecf6007f09'
down_revision: Union[str, None] = '32335e971d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_broken', sa.Boolean(), nullable=True))
    op.alter_column('games', 'dire_win',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('games', 'game_start_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('games', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('games', 'final_processing')
    op.drop_column('games', 'assumed_positions')
    op.drop_column('games', 'broken_replay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('broken_replay', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('assumed_positions', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('final_processing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('games', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'game_start_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('games', 'dire_win',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('games', 'is_broken')
    # ### end Alembic commands ###
