"""fully_aggregated_field

Revision ID: c098e9386e1c
Revises: fb8b9b6cce4f
Create Date: 2024-03-06 23:14:36.377427

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c098e9386e1c'
down_revision: Union[str, None] = 'fb8b9b6cce4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('fully_aggregated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'fully_aggregated')
    # ### end Alembic commands ###
