"""new_index_for_windows

Revision ID: c24d708db2b0
Revises: 44b213778251
Create Date: 2024-04-08 02:46:27.708992

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24d708db2b0'
down_revision: Union[str, None] = '44b213778251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_performance_windows_data_game_performance_id'), 'performance_windows_data', ['game_performance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_windows_data_game_performance_id'), table_name='performance_windows_data')
    # ### end Alembic commands ###
