"""innit

Revision ID: cc3d8fc4bdb0
Revises: 
Create Date: 2025-04-20 23:56:51.387206

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3d8fc4bdb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cdota_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npc_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npc_name_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('img_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_name'), 'heroes', ['name'], unique=True)
    op.create_table('in_game_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('is_tower', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('first_tower_4', sa.Boolean(), nullable=True),
    sa.Column('is_rax', sa.Boolean(), nullable=True),
    sa.Column('melee', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_game_buildings_not_destroyed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('towers_left_top', sa.Integer(), nullable=False),
    sa.Column('towers_left_mid', sa.Integer(), nullable=False),
    sa.Column('towers_left_bottom', sa.Integer(), nullable=False),
    sa.Column('towers_left_throne', sa.Integer(), nullable=False),
    sa.Column('towers_left_total', sa.Integer(), nullable=False),
    sa.Column('rax_left_top', sa.Integer(), nullable=False),
    sa.Column('rax_left_mid', sa.Integer(), nullable=False),
    sa.Column('rax_left_bottom', sa.Integer(), nullable=False),
    sa.Column('rax_left_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pd_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('has_dates', sa.Boolean(), nullable=False),
    sa.Column('has_started', sa.Boolean(), nullable=True),
    sa.Column('has_ended', sa.Boolean(), nullable=True),
    sa.Column('last_parsing_date', sa.BIGINT(), nullable=True),
    sa.Column('parsed_before', sa.Boolean(), nullable=True),
    sa.Column('fully_parsed', sa.Boolean(), nullable=False),
    sa.Column('last_aggregation_date', sa.BIGINT(), nullable=True),
    sa.Column('fully_aggregated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_ranking_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_total_fields',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_window_calculation_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_window_fields',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_windows_table',
    sa.Column('l2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l4', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l6', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l8', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l10', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l12', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l15', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ltotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g5', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g15', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g25', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g35', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g47', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g60', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g60plus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.BIGINT(), nullable=True),
    sa.Column('official_name', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('steam_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approximated_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.account_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dire', sa.Boolean(), nullable=False),
    sa.Column('destroyed_buildings', sa.Integer(), nullable=True),
    sa.Column('destroyed_towers', sa.Integer(), nullable=True),
    sa.Column('destroyed_rax', sa.Integer(), nullable=True),
    sa.Column('destroyed_lane_1', sa.Boolean(), nullable=False),
    sa.Column('destroyed_lane_2', sa.Boolean(), nullable=False),
    sa.Column('destroyed_lane_3', sa.Boolean(), nullable=False),
    sa.Column('megacreeps', sa.Boolean(), nullable=True),
    sa.Column('naked_throne', sa.Boolean(), nullable=True),
    sa.Column('not_destroyed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['not_destroyed_id'], ['in_game_buildings_not_destroyed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facets',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('const_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.SMALLINT(), nullable=True),
    sa.Column('cdota_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gradient_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facets_cdota_name'), 'facets', ['cdota_name'], unique=True)
    op.create_table('performance_ranking_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.account_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['performance_ranking_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_ranking_data_type_id'), 'performance_ranking_data', ['type_id'], unique=False)
    op.create_table('performance_window_calculation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calc_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calc_category_id'], ['performance_window_calculation_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_window_calculation_types_calc_category_id'), 'performance_window_calculation_types', ['calc_category_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_counter', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('sent_team_id', sa.Integer(), nullable=True),
    sa.Column('dire_team_id', sa.Integer(), nullable=True),
    sa.Column('dire_win', sa.Boolean(), nullable=False),
    sa.Column('average_roshan_window_time', sa.Integer(), nullable=True),
    sa.Column('first_ten_kills_dire', sa.Boolean(), nullable=True),
    sa.Column('dire_lost_first_tower', sa.Boolean(), nullable=True),
    sa.Column('dire_building_status_id', sa.Integer(), nullable=True),
    sa.Column('sent_building_status_id', sa.Integer(), nullable=True),
    sa.Column('game_start_time', sa.BIGINT(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('replay_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broken_replay', sa.Boolean(), nullable=True),
    sa.Column('assumed_positions', sa.Boolean(), nullable=True),
    sa.Column('final_processing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dire_building_status_id'], ['buildings_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dire_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['sent_building_status_id'], ['buildings_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_league_id'), 'games', ['league_id'], unique=False)
    op.create_table('in_game_buildings_destroyed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('death_time', sa.Integer(), nullable=False),
    sa.Column('destruction_order', sa.Integer(), nullable=True),
    sa.Column('destruction_order_tower', sa.Integer(), nullable=True),
    sa.Column('destruction_order_rax', sa.Integer(), nullable=True),
    sa.Column('destroyed_lane_1', sa.Boolean(), nullable=False),
    sa.Column('destroyed_lane_2', sa.Boolean(), nullable=False),
    sa.Column('destroyed_lane_3', sa.Boolean(), nullable=False),
    sa.Column('megacreeps', sa.Boolean(), nullable=False),
    sa.Column('naked_throne', sa.Boolean(), nullable=False),
    sa.Column('building_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_data_id'], ['buildings_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['in_game_buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_deaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('death_number', sa.Integer(), nullable=False),
    sa.Column('death_time', sa.Integer(), nullable=False),
    sa.Column('kill_dire', sa.Boolean(), nullable=True),
    sa.Column('killer_hero_id', sa.Integer(), nullable=True),
    sa.Column('killer_player_id', sa.Integer(), nullable=True),
    sa.Column('victim_dire', sa.Boolean(), nullable=True),
    sa.Column('victim_hero_id', sa.Integer(), nullable=True),
    sa.Column('victim_player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['killer_hero_id'], ['heroes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['killer_player_id'], ['players.account_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['victim_hero_id'], ['heroes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['victim_player_id'], ['players.account_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('facet_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('is_roaming', sa.Boolean(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('dire', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('apm', sa.Integer(), nullable=False),
    sa.Column('pings', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['facet_id'], ['facets.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.account_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_game_data_game_id'), 'players_game_data', ['game_id'], unique=False)
    op.create_table('roshan_deaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('death_number', sa.Integer(), nullable=False),
    sa.Column('death_time', sa.Integer(), nullable=False),
    sa.Column('kill_dire', sa.Boolean(), nullable=True),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sides_performance_data',
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('hero_kills', sa.Integer(), nullable=True),
    sa.Column('kills_per_min', sa.Integer(), nullable=True),
    sa.Column('neutral_kills', sa.Integer(), nullable=True),
    sa.Column('roshan_kills', sa.Integer(), nullable=True),
    sa.Column('runes_picked_up', sa.Integer(), nullable=True),
    sa.Column('observer_kills', sa.Integer(), nullable=True),
    sa.Column('observer_uses', sa.Integer(), nullable=True),
    sa.Column('sentry_kills', sa.Integer(), nullable=True),
    sa.Column('sentry_uses', sa.Integer(), nullable=True),
    sa.Column('first_blood_claimed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), nullable=True),
    sa.Column('dire', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sides_performance_data_id'), 'sides_performance_data', ['id'], unique=False)
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.SMALLINT(), nullable=True),
    sa.Column('player_game_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_game_data_id'], ['players_game_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability_performance_data',
    sa.Column('to_heroes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inst_heroes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('to_creeps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inst_creeps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('to_neutrals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inst_neutrals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('by_team_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.BIGINT(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_flat', sa.Boolean(), nullable=True),
    sa.Column('team_cpd_id', sa.Integer(), nullable=True),
    sa.Column('team_cps_id', sa.Integer(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_cpd_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_cps_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_by_team_types_is_flat'), 'by_team_types', ['is_flat'], unique=False)
    op.create_index(op.f('ix_by_team_types_league_id'), 'by_team_types', ['league_id'], unique=False)
    op.create_table('comparison_types',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('is_flat', sa.Boolean(), nullable=True),
    sa.Column('basic', sa.Boolean(), nullable=True),
    sa.Column('cpd_name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cps_name_short', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpd_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cps_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_cpd_id', sa.Integer(), nullable=True),
    sa.Column('player_cps_id', sa.Integer(), nullable=True),
    sa.Column('hero_cpd_id', sa.SMALLINT(), nullable=True),
    sa.Column('hero_cps_id', sa.SMALLINT(), nullable=True),
    sa.Column('facet_cpd_id', sa.SMALLINT(), nullable=True),
    sa.Column('facet_cps_id', sa.SMALLINT(), nullable=True),
    sa.Column('pos_cpd_id', sa.SMALLINT(), nullable=True),
    sa.Column('pos_cps_id', sa.SMALLINT(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facet_cpd_id'], ['facets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facet_cps_id'], ['facets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hero_cpd_id'], ['heroes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hero_cps_id'], ['heroes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_cpd_id'], ['players.account_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_cps_id'], ['players.account_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pos_cpd_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pos_cps_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_types_basic'), 'comparison_types', ['basic'], unique=False)
    op.create_index(op.f('ix_comparison_types_id'), 'comparison_types', ['id'], unique=False)
    op.create_index(op.f('ix_comparison_types_is_flat'), 'comparison_types', ['is_flat'], unique=False)
    op.create_table('cross_comparison_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('position_aggregation_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_comparison_types_league_id'), 'cross_comparison_types', ['league_id'], unique=False)
    op.create_table('data_aggregation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.SMALLINT(), nullable=True),
    sa.Column('facet_id', sa.SMALLINT(), nullable=True),
    sa.Column('position_id', sa.SMALLINT(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facet_id'], ['facets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.account_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_aggregation_types_league_id'), 'data_aggregation_types', ['league_id'], unique=False)
    op.create_index(op.f('ix_data_aggregation_types_patch_id'), 'data_aggregation_types', ['patch_id'], unique=False)
    op.create_table('performance_totals_data',
    sa.Column('gold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('xp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kills_per_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kda', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neutral_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tower_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('courier_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lane_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hero_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observer_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sentry_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roshan_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('runes_picked_up', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ancient_kills', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buyback_count', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observer_uses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sentry_uses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lane_efficiency', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lane_efficiency_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('first_blood_claimed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_kill_time', sa.Integer(), nullable=True),
    sa.Column('died_first', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_death_time', sa.Integer(), nullable=True),
    sa.Column('lost_tower_first', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lost_tower_time', sa.Integer(), nullable=True),
    sa.Column('lost_tower_lane', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('destroyed_tower_first', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('destroyed_tower_lane', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('destroyed_tower_time', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('picked', sa.Integer(), nullable=True),
    sa.Column('first_kill_chance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('first_death_chance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_windows_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calc_type_id', sa.Integer(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.Column('l_empty_mask', sa.SMALLINT(), nullable=True),
    sa.Column('g_empty_mask', sa.SMALLINT(), nullable=True),
    sa.Column('performance_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calc_type_id'], ['performance_window_calculation_types.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performance_table_id'], ['performance_windows_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_windows_data_calc_type_id'), 'performance_windows_data', ['calc_type_id'], unique=False)
    op.create_table('performance_totals_ranking_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_field_id', sa.SMALLINT(), nullable=True),
    sa.Column('performance_ranking_id', sa.Integer(), nullable=True),
    sa.Column('performance_total_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_ranking_id'], ['performance_ranking_data.id'], ),
    sa.ForeignKeyConstraint(['performance_total_data_id'], ['performance_totals_data.id'], ),
    sa.ForeignKeyConstraint(['total_field_id'], ['performance_total_fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_windows_ranking_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_field_id', sa.SMALLINT(), nullable=True),
    sa.Column('performance_ranking_id', sa.Integer(), nullable=True),
    sa.Column('performance_window_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_ranking_id'], ['performance_ranking_data.id'], ),
    sa.ForeignKeyConstraint(['performance_window_data_id'], ['performance_windows_data.id'], ),
    sa.ForeignKeyConstraint(['window_field_id'], ['performance_window_fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_windows_ranking_data')
    op.drop_table('performance_totals_ranking_data')
    op.drop_index(op.f('ix_performance_windows_data_calc_type_id'), table_name='performance_windows_data')
    op.drop_table('performance_windows_data')
    op.drop_table('performance_totals_data')
    op.drop_index(op.f('ix_data_aggregation_types_patch_id'), table_name='data_aggregation_types')
    op.drop_index(op.f('ix_data_aggregation_types_league_id'), table_name='data_aggregation_types')
    op.drop_table('data_aggregation_types')
    op.drop_index(op.f('ix_cross_comparison_types_league_id'), table_name='cross_comparison_types')
    op.drop_table('cross_comparison_types')
    op.drop_index(op.f('ix_comparison_types_is_flat'), table_name='comparison_types')
    op.drop_index(op.f('ix_comparison_types_id'), table_name='comparison_types')
    op.drop_index(op.f('ix_comparison_types_basic'), table_name='comparison_types')
    op.drop_table('comparison_types')
    op.drop_index(op.f('ix_by_team_types_league_id'), table_name='by_team_types')
    op.drop_index(op.f('ix_by_team_types_is_flat'), table_name='by_team_types')
    op.drop_table('by_team_types')
    op.drop_table('ability_performance_data')
    op.drop_table('performances')
    op.drop_index(op.f('ix_sides_performance_data_id'), table_name='sides_performance_data')
    op.drop_table('sides_performance_data')
    op.drop_table('roshan_deaths')
    op.drop_index(op.f('ix_players_game_data_game_id'), table_name='players_game_data')
    op.drop_table('players_game_data')
    op.drop_table('hero_deaths')
    op.drop_table('in_game_buildings_destroyed')
    op.drop_index(op.f('ix_games_league_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_performance_window_calculation_types_calc_category_id'), table_name='performance_window_calculation_types')
    op.drop_table('performance_window_calculation_types')
    op.drop_index(op.f('ix_performance_ranking_data_type_id'), table_name='performance_ranking_data')
    op.drop_table('performance_ranking_data')
    op.drop_index(op.f('ix_facets_cdota_name'), table_name='facets')
    op.drop_table('facets')
    op.drop_table('buildings_data')
    op.drop_table('approximated_positions')
    op.drop_table('teams')
    op.drop_table('positions')
    op.drop_table('players')
    op.drop_table('performance_windows_table')
    op.drop_table('performance_window_fields')
    op.drop_table('performance_window_calculation_categories')
    op.drop_table('performance_total_fields')
    op.drop_table('performance_ranking_types')
    op.drop_table('patches')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('in_game_buildings_not_destroyed')
    op.drop_table('in_game_buildings')
    op.drop_index(op.f('ix_heroes_name'), table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###
