"""fix_2

Revision ID: cdfac9826210
Revises: b75f0a38217f
Create Date: 2025-05-17 03:16:24.956073

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfac9826210'
down_revision: Union[str, None] = 'b75f0a38217f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'lane_efficiency',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Numeric(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('performance_totals_data', 'lane_efficiency_pct',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_totals_data', 'lane_efficiency_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('performance_totals_data', 'lane_efficiency',
               existing_type=sa.Numeric(precision=4, scale=3),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
