"""gameData

Revision ID: d698b51a009e
Revises: c24d708db2b0
Create Date: 2024-04-22 02:02:35.303608

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd698b51a009e'
down_revision: Union[str, None] = 'c24d708db2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('hero_kills', sa.Integer(), nullable=True),
    sa.Column('kpm', sa.Integer(), nullable=True),
    sa.Column('roshan_kills', sa.Integer(), nullable=True),
    sa.Column('runes_picked_up', sa.Integer(), nullable=True),
    sa.Column('obs_placed', sa.Integer(), nullable=True),
    sa.Column('obs_kills', sa.Integer(), nullable=True),
    sa.Column('sentry_placed', sa.Integer(), nullable=True),
    sa.Column('sentry_kills', sa.Integer(), nullable=True),
    sa.Column('first_blood_claimed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_data_id'), 'games_data', ['id'], unique=False)
    op.add_column('games', sa.Column('sent_game_data_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('dire_game_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'games_data', ['sent_game_data_id'], ['id'])
    op.create_foreign_key(None, 'games', 'games_data', ['dire_game_data_id'], ['id'])
    op.drop_index('ix_performance_data_types_is_comparable', table_name='performance_data_types')
    op.drop_column('performance_data_types', 'is_comparable')
    op.drop_column('performance_data_types', 'sum_to_agg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_data_types', sa.Column('sum_to_agg', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('performance_data_types', sa.Column('is_comparable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_performance_data_types_is_comparable', 'performance_data_types', ['is_comparable'], unique=False)
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'dire_game_data_id')
    op.drop_column('games', 'sent_game_data_id')
    op.drop_index(op.f('ix_games_data_id'), table_name='games_data')
    op.drop_table('games_data')
    # ### end Alembic commands ###
