"""building data

Revision ID: d9f2d32e2759
Revises: 2ccd4e3b93f3
Create Date: 2025-07-09 06:39:40.209537

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f2d32e2759'
down_revision: Union[str, None] = '2ccd4e3b93f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_buildings_data_game_id_performances', 'buildings_data', type_='foreignkey')
    op.create_foreign_key(None, 'buildings_data', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buildings_data', type_='foreignkey')
    op.create_foreign_key('fk_buildings_data_game_id_performances', 'buildings_data', 'performances', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
