"""remove_excessive_cross_comparison

Revision ID: e082f48fedaf
Revises: 43ed994de140
Create Date: 2024-03-10 23:48:00.774706
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel import text
from sqlmodel.orm.session import Session



# revision identifiers, used by Alembic.
revision: str = 'e082f48fedaf'
down_revision: Union[str, None] = '43ed994de140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison_types', 'cross_comparison')
    op.drop_column('data_aggregation_types', 'cross_comparison')
    op.add_column('games_performance', sa.Column('cross_comparison', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""UPDATE games_performance SET cross_comparison = false""")
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games_performance', 'cross_comparison')
    op.add_column('data_aggregation_types', sa.Column('cross_comparison', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('comparison_types', sa.Column('cross_comparison', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
