"""new_fields

Revision ID: e55b20e4924c
Revises: 77ba22f39f6a
Create Date: 2025-06-15 21:41:54.985857

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55b20e4924c'
down_revision: Union[str, None] = '77ba22f39f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('first_pick_pos_1', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_pos_2', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_pos_3', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_pos_4', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('first_pick_pos_5', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('win_dire', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('win_sent', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_totals_data', 'win_sent')
    op.drop_column('performance_totals_data', 'win_dire')
    op.drop_column('performance_totals_data', 'first_pick_pos_5')
    op.drop_column('performance_totals_data', 'first_pick_pos_4')
    op.drop_column('performance_totals_data', 'first_pick_pos_3')
    op.drop_column('performance_totals_data', 'first_pick_pos_2')
    op.drop_column('performance_totals_data', 'first_pick_pos_1')
    # ### end Alembic commands ###
