"""league_model_fix_v2

Revision ID: eebabf9abf35
Revises: 07242aeb9e5e
Create Date: 2024-01-22 12:40:42.581261

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'eebabf9abf35'
down_revision: Union[str, None] = '07242aeb9e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('has_dates', sa.Boolean(), nullable=False))
    op.add_column('leagues', sa.Column('has_started', sa.Boolean(), nullable=True))
    op.add_column('leagues', sa.Column('has_ended', sa.Boolean(), nullable=True))
    op.drop_column('leagues', 'ended')
    op.drop_column('leagues', 'started')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('started', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('ended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('leagues', 'has_ended')
    op.drop_column('leagues', 'has_started')
    op.drop_column('leagues', 'has_dates')
    # ### end Alembic commands ###
