"""cross_comparison

Revision ID: f1dc12453689
Revises: a5590fcc0f15
Create Date: 2024-03-10 21:19:16.039305

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel import text
from sqlmodel.orm.session import Session


# revision identifiers, used by Alembic.
revision: str = 'f1dc12453689'
down_revision: Union[str, None] = 'a5590fcc0f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_types', sa.Column('cross_comparison', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as sqlmodel_session:
        sqlmodel_session.execute(
            text("""UPDATE comparison_types SET cross_comparison = false""")
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison_types', 'cross_comparison')
    # ### end Alembic commands ###
