"""league_field2

Revision ID: f5530a5df7a4
Revises: afba04ad0ea9
Create Date: 2025-06-29 04:04:57.192231

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5530a5df7a4'
down_revision: Union[str, None] = 'afba04ad0ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('should_be_processed', sa.Boolean(), nullable=True))
    op.drop_column('leagues', 'waiting_for_agg')
    op.drop_column('leagues', 'waiting_for_ccomp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('waiting_for_ccomp', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('leagues', sa.Column('waiting_for_agg', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('leagues', 'should_be_processed')
    # ### end Alembic commands ###
