"""field fix

Revision ID: f594ccb01231
Revises: 3f3037978934
Create Date: 2025-04-06 23:35:02.505218

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f594ccb01231'
down_revision: Union[str, None] = '3f3037978934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sides_performance_data', 'game_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sides_performance_data', 'game_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
