"""advantage fields

Revision ID: f5ce95cb1c38
Revises: 25e56a017b43
Create Date: 2025-07-17 16:32:09.734404

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ce95cb1c38'
down_revision: Union[str, None] = '25e56a017b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_totals_data', sa.Column('gold_advantage', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('gold_advantage_win', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('performance_totals_data', sa.Column('gold_advantage_lose', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance_totals_data', 'gold_advantage_lose')
    op.drop_column('performance_totals_data', 'gold_advantage_win')
    op.drop_column('performance_totals_data', 'gold_advantage')
    # ### end Alembic commands ###
