"""processed_at_fields

Revision ID: fd455316f124
Revises: f5ce95cb1c38
Create Date: 2025-07-24 21:10:00.278642

"""
from typing import Sequence, Union

from db import SQLModel
import sqlmodel.sql.sqltypes

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd455316f124'
down_revision: Union[str, None] = 'f5ce95cb1c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.drop_column('leagues', 'should_be_processed')
    op.add_column('patches', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.drop_column('patches', 'should_be_processed')
    op.execute("UPDATE patches SET processed_at = NOW()")
    op.execute("UPDATE leagues SET processed_at = NOW()")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('should_be_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('patches', 'processed_at')
    op.add_column('leagues', sa.Column('should_be_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('leagues', 'processed_at')
    # ### end Alembic commands ###
